-d C:\Users\gay_n\Documents\FPGA_PROJECTS\HDMI_NIC\hDMI\FPGA_HDMI\impl\gwsynthesis\hDMI.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\gay_n\Documents\FPGA_PROJECTS\HDMI_NIC\hDMI\FPGA_HDMI\src\hDMI.cst
-cfg C:\Users\gay_n\Documents\FPGA_PROJECTS\HDMI_NIC\hDMI\FPGA_HDMI\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
